site_name: Sheeep's Zone
site_url: https://qiqiqihy.github.io/Sheeep-Zone/
repo_url: https://github.com/qiqiqihy/Sheeep-Zone
repo_name: qiqiqihy/Sheeep-Zone
site_author: qiqiqihy
site_description: A blog about SLAM and more.

docs_dir: docs
site_dir: site

theme:
  name: material
  features:
    - navigation.tabs
    - search.suggest
    - content.code.annotate
    - content.code.copy
    # - content.code.select
  font:
    text: Noto Sans SC
    code: Roboto Mono

nav:
  - Home: index.md
  - SLAM Basics:
      - SIFT特征: SLAM-Basics-SIFT.md
      # - GFTT: SLAM-Basics-GFTT.md
      # - SURF: SLAM-Basics-SURF.md
  - 深入理解计算机系统:
      - Ch1.计算机系统漫游: cs-ch1.md

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/figure-ref.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js